config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  as :user do
    get 'users', to: "profiles#dash", as: :user_root
  end

  get :dash, to: "profiles#dash"
  get :go_premium, to: "profiles#go_premium", as: :go_premium
  get :go_pro, to: "profiles#go_pro", as: :go_pro
  get :ftoggle, to: "profiles#filter_toggle", as: :ftoggle
  get :filters, to: "profiles#filters", as: :filters
  get :filterall, to: "profiles#filter_all", as: :filterall

  resources :polls, except: [:edit, :update] do
    member do
      post :answer, to: "polls#add_answer"
      get :toggle, to: "polls#toggle"
      post :result, to: "polls#result"
      get :share, to: "polls#share"
      get :report, to: "polls#report"
    end

    collection do
      get :manage, to: "polls#manage", as: :manage
      get :answered, to: "polls#answered", as: :answered
      get :sponsored, to: "polls#sponsored", as: :sponsored
      get :fresh, to: "polls#fresh", as: :fresh
      get :loved, to: "polls#loved", as: :loved
      get :funny, to: "polls#funny", as: :funny
      get :interesting, to: "polls#interesting", as: :interesting
      get :friend, to: "polls#friend", as: :friend
    end
  end

  resources :friends, only: :index do
    get :add, to: "friends#add", as: :add
    get :remove, to: "friends#remove", as: :remove
    get :block, to: "friends#block", as: :block
    get :dash, to: "friends#dash", as: :fdash
  end
end

app/views/shared/_filter-sidebar.html.erb
<div class="filter-sidebar">

  <% Category.all.each do |cat| %>

    <div class="filter-col-desktop col-6 col-sm-4 col-md-3">

      <% cat_filter = Filter.find_by(user: current_user, category: cat) %>
      <% status_active = cat_filter.nil? || (!cat_filter.nil? && cat_filter.active) %>

      <%= link_to ftoggle_path(cat_id: cat.id, origin_action: action_name, query: params[:query], friend_id: params[:friend_id].to_i) do %>
        <% if status_active %>
          <div class="category cat-active" style="border: none; background-color: transparent;" data-category="<%= cat.id %>">
            <%= image_tag("category_color/#{cat.icon}", size: "40x40",  title: "#{cat.name}", data: { toggle: "tooltip" },class: "svg-icon", alt: "#{cat.name} selected") %>
          </div>
        <% else %>
          <div class="category cat-inactive" style="border: none; background-color: transparent;" data-category="<%= cat.id %>">
            <%= image_tag("category_lgrey/#{cat.icon}", size: "40x40", title: "#{cat.name}", data: { toggle: "tooltip" }, class: "svg-icon", alt: "#{cat.name} not selected") %>
          </div>
        <% end %>
      <% end %>

    </div>

  <% end %>

  <div class="filter-col-desktop col-6 col-sm-4 col-md-3">
    <%= link_to filterall_path(active: true, origin_action: action_name, query: params[:query], friend_id: params[:friend_id].to_i) do %>
      <div class="category cat-inactive" style="border: none; background-color: transparent;">
        <%= image_tag("category_lgrey/all.svg", size: "40x40", title: "Select All", data: { toggle: "tooltip" }, class: "svg-icon", alt: "Select all") %>
      </div>
    <% end %>
  </div>

  <div class="filter-col-desktop col-6 col-sm-4 col-md-3">
    <%= link_to filterall_path(active: false, origin_action: action_name, query: params[:query], friend_id: params[:friend_id].to_i) do %>
      <div class="category cat-inactive" style="border: none; background-color: transparent;">
        <%= image_tag("category_lgrey/none.svg", size: "40x40", title: "Remove All", data: { toggle: "tooltip" }, class: "svg-icon", alt: "Select all") %>
      </div>
    <% end %>
  </div>

</div>

app/views/shared/_flashes.html.erb
<%# if notice %>
<!--   <div class="alert alert-info alert-dismissible fade show m-1" role="alert"> -->
    <%#= notice %>
<!--     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div> -->
<%# end %>
<% if alert %>
  <div class="modal fade" id="alertModal" tabindex="-1" role="dialog" aria-labelledby="alertModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="alertModalLabel">Alert</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= alert %>
    </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="<%= 'footer-home' if controller_name == "pages" %>">

  <div class="footer-left">
    <p>
      &#169; <%= Time.now.strftime("%Y") %> Nuno Loureiro
      <span><a href="https://github.com/nloureiro88" target="_blank"><i class="fab fa-github fa-lg"></i></a></span>
      <span><a href="https://www.linkedin.com/in/nuno-loureiro-95815a5a/" target="_blank"><i class="fab fa-linkedin-in fa-lg"></i></a></span>
    </p>
  </div>

  <div class="footer-right">
    <p>
      <span><a href="#" data-toggle="modal" data-target="#aboutModal">About</a></span>
      <span><a href="#" data-toggle="modal" data-target="#tcModal">Terms & Conditions</a></span>
      <span><a href="#go-top">Up <i class="fas fa-caret-up"></i></a></span>
    </p>
  </div>

  <div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="aboutModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="aboutModalLabel">About</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>PollGod is a training project by Nuno Loureiro right after concluding the 9-week Le Wagon coding bootcamp focused on web development and, more specifically, Ruby on Rails.</p> <br>
        <p>This project was developed over the course of 2 weeks with the goal of prototyping the core features of the PollGod concept with desktop and mobile interfaces.</p> <br>
        <p>If you are interesting in knowing more about this project, my portfolio or my career, do not hesitate to contact me through <a href="https://github.com/nloureiro88">Github</a> or <a href="https://www.linkedin.com/in/nuno-loureiro-95815a5a/">LinkedIn</a>.</p>
      </div>
      <div class="modal-footer">
        <a class="button btn btn-secondary" href="mailto:nunoloureiro88@gmail.com">E-mail</a>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="tcModal" tabindex="-1" role="dialog" aria-labelledby="tcModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="tcModalLabel">Terms & Conditions</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>PollGod is a training project not meant for profit at this stage and, as such, there is no guarantee of user support, bug fixing, new releases or any other type of ongoing activity or responsability.</p> <br>
        <p>All the data added to the app, including personal data, is subject to standard Rails protection; however, considering the project context and scope (see 'About' section), the information is provided by the users at their own risk and without any safeguards guaranteed.</p> <br>
        <p>All of the features and underlying code are protected throught standard intellectual property and copyright laws and regulation.</p> <br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>

</footer>

app/views/shared/_friendlist.html.erb
<div class="container-fluid friend-list">
  <div class="row friend-list-row">

  <% @friends.each do |friend| %>

    <%= link_to friend_fdash_path(friend_id: friend.id) do %>

      <div class="friend-card">

        <div class="friend-card-content">

          <div class="friend-card-left">
            <% if friend.photo.file.nil? %>
              <%= image_tag "avatar/#{friend.birthdate.day}.svg", size: "50x50", class: "avatar-xl" %>
            <% else %>
              <%= cl_image_tag("#{friend.photo}", size: "50x50", crop: :thumb, gravity: :face, class: "avatar-xl") %>
            <% end %>

            <% friend_stats = friend.stats %>
            <ul class="friend-stats">
              <li title="Followers" data-toggle="tooltip"><i class="fas fa-users"></i> <%= friend_stats[:followers] %></li>
              <li title="Polls" data-toggle="tooltip"><i class="fas fa-poll-h"></i> <%= friend_stats[:polls] %></li>
              <li title="Answers" data-toggle="tooltip"><i class="fas fa-vote-yea"></i> <%= friend_stats[:answers] %></li>
              <li title="Tickets" data-toggle="tooltip"><i class="fas fa-ticket-alt"></i> <%= number_with_delimiter(friend_stats[:tickets], delimiter: '.') %></li>
            </ul>
          </div>

          <div class="friend-card-right">
              <p><%= friend.first_name %> <strong><%= friend.last_name %></strong></p>

              <ul class="friend-info">
                <li><strong><%= friend.subscription.capitalize %></strong></li>
                <li><%= friend.gender.capitalize %>, <%= friend.age %></li>
                <li><%= friend.profession %></li>
                <li><%= friend.location %></li>
              </ul>
          </div>

          <%= link_to friend_remove_path(friend.id, origin_action: action_name, origin_controller: controller_name), class: "delete-link" do %>
            <i class="fas fa-user-minus fa-sm" title="Remove Follow" data-toggle="tooltip"></i>
          <% end %>

          <%= link_to friend_polls_path(friend_id: friend.id, origin_action: action_name, origin_controller: controller_name), class: "go-poll-link" do %>
            <i class="fas fa-poll-h fa-sm" title="See Polls" data-toggle="tooltip"></i>
          <% end %>

        </div>

      </div>

    <% end %>

  <% end %>

  <div class="filling-empty-space-childs-polls"></div>
  <div class="filling-empty-space-childs-polls"></div>

  </div>
</div>

app/views/shared/_index-page.html.erb
<div class="container list-page">

    <div class="column center-column">

      <div class="page-header">
        <% if controller_name == 'polls' && action_name == 'index'  %>
          <h2><i class="fas fa-trophy"></i> Top</h2>
        <% elsif controller_name == 'polls' && action_name == 'loved' %>
          <h2><i class="fas fa-heart"></i> Loved</h2>
        <% elsif controller_name == 'polls' && action_name == 'funny' %>
          <h2><i class="fas fa-grin-squint"></i> Funny</h2>
        <% elsif controller_name == 'polls' && action_name == 'interesting' %>
          <h2><i class="fas fa-trophy"></i> Interesting</h2>
        <% elsif controller_name == 'polls' && action_name == 'sponsored' %>
          <h2><i class="fas fa-wallet"></i> Sponsored</h2>
        <% elsif controller_name == 'polls' && action_name == 'fresh' %>
          <h2><i class="fas fa-paint-roller"></i> Fresh</h2>
        <% elsif controller_name == 'polls' && action_name == 'manage' %>
          <h2><i class="fas fa-poll-h"></i> My Polls</h2>
        <% elsif controller_name == 'polls' && action_name == 'answered' %>
          <h2><i class="fas fa-trophy"></i> My Answers</h2>
        <% elsif controller_name == 'friends' && action_name == 'index' %>
          <h2><i class="fas fa-users"></i> Following</h2>
        <% elsif controller_name == 'polls' && action_name == 'friend' %>
          <h2><i class="fas fa-users"></i> <%= User.find(params[:friend_id]).first_name %> <%= User.find(params[:friend_id]).last_name %> </h2>
          <div class="friend-btn" style="display:flex; max-width: 400px; margin: 1rem auto;">
            <%= link_to ' My Follows '.html_safe, friends_path, class: "btn btn-back" %>
            <%= link_to ' Dashboard '.html_safe, friend_fdash_path(friend_id: params[:friend_id]), class: "btn btn-back" %>
          </div>
        <% end %>

        <% if @polls.size.zero? || @polls.nil? %>
          <% if action_name == 'manage' && Poll.where(user: current_user).count.zero? %>
            <h3> No results found <i class="far fa-sad-tear"></i>, create your first poll and you'll see it in this page!</h3>
          <% elsif action_name == 'answered' && Answer.where(user: current_user).count.zero? %>
            <h3> No results found <i class="far fa-sad-tear"></i>, answer your first poll and you'll see it in this page!</h3>
          <% else %>
            <h3> No results found <i class="far fa-sad-tear"></i>, please try to adjust your search and filters...</h3>
          <% end %>
        <% end %>
      </div>

      <%= render 'shared/pollist', locals: {polls: @polls}  %>
    </div>

    <%= render 'shared/filter-sidebar' %>
</div>

app/views/shared/_navbar.html.erb
<% searcheable_actions = ['index', 'loved', 'funny', 'interesting', 'sponsored', 'fresh', 'manage', 'answered', 'friend'] %>
<% outer_actions = ['index', 'loved', 'funny', 'interesting', 'sponsored', 'fresh'] %>

<!-- NAVBAR DESKTOP -->

  <div class="navbar fixed-top navbar-light navbar-lewagon navbar-lewagon-desktop">

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-big-contrast.png" %>
    <% end %>

    <div class="navbarSearch" id="navbarSearchDesktop">
      <% if controller_name == 'polls' && searcheable_actions.include?(action_name) %>
        <%= form_tag ({controller: controller_name, action: action_name}), method: :get, class: "search-form" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "e.g. #{ current_user.hobbies.empty? ? 'Game of thrones' : current_user.hobbies.split(", ").first.downcase.capitalize }"
          %>
          <%= button_tag(type: 'submit', class: "btn btn-default", id: "submit-search") do %>
            <i class="fas fa-search"></i>
          <% end %>
          <%= link_to ({controller: controller_name, action: action_name}), id: "clear-search" do %>
            <i class="fas fa-times"></i>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="dropleft">
      <div class="navbar-profile-section" style="width: 153px">
        <button id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_user.photo.file.nil? %>
            <%= image_tag "avatar/#{User.last.birthdate.day}.svg", size: "48x48" %>
          <% else %>
            <%= cl_image_tag "#{current_user.photo}", size: "48x48", crop: :thumb, gravity: :face %>
          <% end %>
        </button>
        <div class="dropdown-menu" style="right: 55px; top: 5px">
          <%= link_to "Dashboard", dash_path, class: "nav-link" %>
          <%= link_to "Following", friends_path, class: "nav-link" %>
          <%= link_to "My Polls", manage_polls_path, class: "nav-link" %>
          <%= link_to "My Answers", answered_polls_path, class: "nav-link" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Edit Profile", user_registration_path, method: :patch, class: "nav-link" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </div>
      </div>
    </div>

  </div>

<!-- NAVBAR MOBILE -->

  <div class="navbar fixed-top navbar-light navbar-lewagon navbar-lewagon-mobile">

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-big-contrast.png" %>
    <% end %>

    <div class="navbar-toggles">

      <% if controller_name == 'polls' && searcheable_actions.include?(action_name) %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSearchMobile" aria-controls="navbarSearch" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-search" style= "<%= 'color: #9FCDD0 !important' if params[:query].present? %>"></i>
        </button>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarOption" aria-controls="navbarOption" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-poll" style= "<%= 'color: #9FCDD0 !important' if (outer_actions.include?(action_name) && controller_name == 'polls') %>"></i>
      </button>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarProfile" aria-controls="navbarProfile" aria-expanded="false" aria-label="Toggle navigation">
        <% if current_user.photo.file.nil? %>
          <%= image_tag "avatar/#{User.last.birthdate.day}.svg", size: "32x32" %>
        <% else %>
          <%= cl_image_tag "#{current_user.photo}", size: "32x32", crop: :thumb, gravity: :face %>
        <% end %>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="navbarProfile">
      <div class="navbar-cont">
        <ul class="navbar-nav mr-auto navbar-left">
          <li class="nav-item <%= 'active' if controller_name == 'profiles' && action_name == 'dash' %>">
            <%= link_to "Dashboard", dash_path, class: "nav-link" %>
          </li>
          <li style="color: white" class="nav-item <%= 'active' if ((controller_name == 'polls' && action_name == 'friend') || controller_name == 'friends') %>">
            <%= link_to "Following", friends_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav mr-auto navbar-center">
          <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'manage' %>">
            <%= link_to "My Polls", manage_polls_path(query: params[:query]), class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'answered' %>">
            <%= link_to "My Answers", answered_polls_path(query: params[:query]), class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav mr-auto navbar-right">
          <li style="color: white" class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'new' %>">
            <%= link_to "New Poll", new_poll_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if controller_name == 'profiles' && action_name == 'filters' %>">
            <%= link_to "Filters", filters_path, class: "nav-link" %>
          </li>
          <!-- <li class="nav-item">
            <%#= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li> -->
        </ul>
      </div>
    </div>

    <div class="collapse navbar-collapse" id="navbarOption">
      <div class="navbar-cont">
        <ul class="navbar-nav mr-auto navbar-left">
          <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'index' %>">
            <%= link_to "Top", polls_path(query: params[:query]), class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'loved' %>">
            <%= link_to "Loved", loved_polls_path(query: params[:query]), class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav mr-auto navbar-center">
          <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'funny' %>">
            <%= link_to "Funny", funny_polls_path(query: params[:query]), class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'interesting' %>">
            <%= link_to "Interesting", interesting_polls_path(query: params[:query]), class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav mr-auto navbar-right">
          <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'sponsored' %>">
            <%= link_to "Sponsored", sponsored_polls_path(query: params[:query]), class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'fresh' %>">
            <%= link_to "Fresh", fresh_polls_path(query: params[:query]), class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>

    <% if controller_name == 'polls' && searcheable_actions.include?(action_name) %>

      <div class="collapse navbar-collapse navbarSearch" id="navbarSearchMobile">
        <%= form_tag ({controller: controller_name, action: action_name}), method: :get, class: "search-form" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "e.g. #{ current_user.hobbies.empty? ? 'Game of thrones' : current_user.hobbies.split(", ").first.downcase.capitalize }"
          %>
          <%= link_to ({controller: controller_name, action: action_name}), id: "clear-search" do %>
            <i class="fas fa-times"></i>
          <% end %>
        <% end %>
      </div>

    <% end %>

  </div>

app/views/shared/_navigator.html.erb
<div class="navigator">

  <ul class="navigator-create">
    <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'new' %>">
      <%= link_to new_poll_path, class: "nav-link" do %>
        <div class="icon-container">
          <i class="fas fa-plus-square"></i>
        </div>
        <span>New Poll</span>
      <% end %>
    </li>
  </ul>

  <ul class="navigation-mine">
    <li class="nav-item <%= 'active' if controller_name == 'profiles' && action_name == 'dash' %>">
      <%= link_to dash_path, class: "nav-link" do %>
        <div class="icon-container">
          <i class="fas fa-tachometer-alt"></i>
        </div>
        <span>Dashboard</span>
      <% end %>
    </li>
    <li class="nav-item <%= 'active' if (controller_name == 'polls' && action_name == 'friend') || controller_name == 'friends' %>">
      <%= link_to friends_path, class: "nav-link" do %>
        <div class="icon-container">
          <i class="fas fa-users"></i>
        </div>
        <span>Following</span>
      <% end %>
    </li>
    <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'manage' %>">
      <%= link_to manage_polls_path, class: "nav-link" do %>
        <div class="icon-container">
          <i class="fas fa-poll-h"></i>
        </div>
        <span>My Polls</span>
      <% end %>
    </li>
    <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'answered' %>">
      <%= link_to answered_polls_path, class: "nav-link" do %>
        <div class="icon-container">
          <i class="fas fa-vote-yea"></i>
        </div>
        <span>My Answers</span>
      <% end %>
    </li>
  </ul>

  <ul class="navigator-list">
    <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'index' %>">
      <%= link_to polls_path, class: "nav-link" do %>
        <div class="icon-container">
          <i class="fas fa-trophy"></i>
        </div>
        <span>Top</span>
      <% end %>
    </li>
    <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'loved' %>">
      <%= link_to loved_polls_path, class: "nav-link" do %>
        <div class="icon-container">
          <i class="fas fa-heart"></i>
        </div>
        <span>Loved</span>
      <% end %>
    </li>
    <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'funny' %>">
      <%= link_to funny_polls_path, class: "nav-link" do %>
        <div class="icon-container">
          <i class="fas fa-grin-squint"></i>
        </div>
        <span>Funny</span>
      <% end %>
    </li>
    <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'interesting' %>">
      <%= link_to interesting_polls_path, class: "nav-link" do %>
        <div class="icon-container">
          <i class="fas fa-graduation-cap"></i>
        </div>
        <span>Interesting</span>
      <% end %>
    </li>
    <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'sponsored' %>">
      <%= link_to sponsored_polls_path, class: "nav-link" do %>
        <div class="icon-container">
          <i class="fas fa-wallet"></i>
        </div>
        <span>Sponsored</span>
      <% end %>
    </li>
    <li class="nav-item <%= 'active' if controller_name == 'polls' && action_name == 'fresh' %>">
      <%= link_to fresh_polls_path, class: "nav-link" do %>
        <div class="icon-container">
          <i class="fas fa-paint-roller"></i>
        </div>
        <span>Fresh</span>
      <% end %>
    </li>
  </ul>

  <% quicksearch_actions = ['index', 'loved', 'funny', 'interesting', 'sponsored', 'fresh', 'friend'] %>
  <% if controller_name == 'polls' && quicksearch_actions.include?(action_name) %>

    <ul class="quick-searches">

      <li class="nav-item">
        <%= link_to "#", class: "nav-link quick-go" do %>
          <div class="icon-container">
            <i class="fas fa-tags"></i>
          </div>
          <span>Quick Search</span>
          <span class="float-right"><i class="fas fa-chevron-right" style="font-size: 0.8rem;"></i></span>
        <% end %>
      </li>

      <div id="quick-search">
        <ul>
          <% @quick_links.take(20).each do |quick_link| %>
            <li class="quick-link"><%= link_to quick_link, ({controller: controller_name, action: action_name, query: quick_link}), class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>

    </ul>

  <% end %>

</div>