config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  as :user do
    get 'users', to: "profiles#dash", as: :user_root
  end

  get :dash, to: "profiles#dash"
  get :go_premium, to: "profiles#go_premium", as: :go_premium
  get :go_pro, to: "profiles#go_pro", as: :go_pro
  get :ftoggle, to: "profiles#filter_toggle", as: :ftoggle
  get :filters, to: "profiles#filters", as: :filters
  get :filterall, to: "profiles#filter_all", as: :filterall

  resources :polls, except: [:edit, :update] do
    member do
      post :answer, to: "polls#add_answer"
      get :toggle, to: "polls#toggle"
      post :result, to: "polls#result"
      get :share, to: "polls#share"
      get :report, to: "polls#report"
    end

    collection do
      get :manage, to: "polls#manage", as: :manage
      get :answered, to: "polls#answered", as: :answered
      get :sponsored, to: "polls#sponsored", as: :sponsored
      get :fresh, to: "polls#fresh", as: :fresh
      get :loved, to: "polls#loved", as: :loved
      get :funny, to: "polls#funny", as: :funny
      get :interesting, to: "polls#interesting", as: :interesting
      get :friend, to: "polls#friend", as: :friend
    end
  end

  resources :friends, only: :index do
    get :add, to: "friends#add", as: :add
    get :remove, to: "friends#remove", as: :remove
    get :block, to: "friends#block", as: :block
    get :dash, to: "friends#dash", as: :fdash
  end
end

app/models/poll.rb
class Poll < ApplicationRecord

  # Relationships
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :active_users, class_name: "User", foreign_key: :active_user_id
  has_many :follow_users, class_name: "User", foreign_key: :follow_user_id

  # Search
  include PgSearch
  pg_search_scope :poll_search,
    against: [ :question, :tags ],
    associated_against: {
      user: [ :first_name, :last_name ],
      category: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }

  # Lists
  QTYPES = ['open', 'closed', 'sponsored']
  OTYPES = ['SCP', 'MCP'] # To increment in the future
  STATUS = ['active', 'inactive', 'deleted']

  # Validations
  validates :user_id, presence: true, allow_blank: false
  validates :category_id, presence: true, allow_blank: false
  validates :points, presence: true, numericality: { only_integer: true, greater_then: 0 }
  validates :qtype, presence: true, inclusion: { in: QTYPES }
  validates :optype, presence: true, inclusion: { in: OTYPES }
  validates :question, presence: true, length: { maximum: 80 } # Consider uniqueness: true for real data
  validates :deadline, presence: true, allow_blank: false
  validates :status, presence: true, inclusion: { in: STATUS }
  validates :tags, length: { maximum: 45 }
  validate :val_options

  def like_hash
    like_hash = { love: 0, funny: 0, interest: 0 }
    active_answers = self.answers.where("status != 'deleted'")
    like_hash[:love] += active_answers.where(f_love: true).count
    like_hash[:funny] += active_answers.where(f_funny: true).count
    like_hash[:interest] += active_answers.where(f_interest: true).count
    like_hash
  end

  def refresh_likes
    result_hash = like_hash
    self.t_love = result_hash[:love]
    self.t_funny = result_hash[:funny]
    self.t_interest = result_hash[:interest]
    self.t_likes = result_hash.values.sum
    self.save!
  end

  def count_answers
    self.answers.where("status != 'deleted'").count
  end

  def answer(user)
    self.answers.where("status != 'deleted' AND user_id = ?", user.id)
  end

  def answered?(user)
    self.answer(user).count.positive?
  end

  def results
    result_hash = Hash.new(0)
    self.options.each_with_index do |_opt, index|
      result_hash[index] += Answer.where("status != 'deleted' AND poll_id = ? AND answer = ?", self.id, index.to_s).count
    end
    result_hash
  end

  def gender_stats
    result_hash = {}
    result_hash[:men] = []
    result_hash[:women] = []

    self.options.each_with_index do |_opt, index|
      answers = Answer.where("status != 'deleted' AND poll_id = ? AND answer = ?", self.id, index.to_s)
      result_hash[:men] << answers.select { |a| a.user.gender == 'Male' }.count
      result_hash[:women] << answers.select { |a| a.user.gender == 'Female' }.count
    end
    result_hash
  end

  def age_stats
    result_hash = Hash.new { |h, k| h[k] = [] }

    self.options.each_with_index do |_opt, index|
      answers = Answer.where("status != 'deleted' AND poll_id = ? AND answer = ?", self.id, index.to_s)
      result_hash[:m25] << answers.select { |a| a.user.age < 25 }.count
      result_hash[:m35] << answers.select { |a| a.user.age >= 25 && a.user.age < 35 }.count
      result_hash[:m45] << answers.select { |a| a.user.age >= 35 && a.user.age < 45 }.count
      result_hash[:m55] << answers.select { |a| a.user.age >= 45 && a.user.age < 55 }.count
      result_hash[:m55] << answers.select { |a| a.user.age >= 55 }.count
    end
    result_hash
  end

  def top_profs
    answers = Answer.where(poll: self, status: 'active').order(:created_at)
    prof_hash = Hash.new(0)

    answers.each do |ans|
      user_prof = ans.user.profession
      prof_hash[user_prof] += 1
    end

    prof_hash.sort_by {|k, v| [-v, k] }.take(8)
  end

  def prof_stats
    profs = top_profs
    result_hash = Hash.new { |h, k| h[k] = [] }

    profs.each do |prof, _value|
      self.options.each_with_index do |_opt, index|
        result_hash[index] << User.joins('INNER JOIN answers ON users.id = answers.user_id')
                                  .where('profession = ? AND answers.poll_id = ? AND answers.status = ? AND answers.answer = ?',
                                          prof, self, 'active', index.to_s).count
      end
    end

    result_hash
  end

  def top_countries
    answers = Answer.where(poll: self, status: 'active').order(:created_at)
    country_hash = Hash.new(0)

    answers.each do |ans|
      user_country = ans.user.location
      country_hash[user_country] += 1
    end

    country_hash.sort_by {|k, v| [-v, k] }.take(8)
  end

  def country_stats
    countries = top_countries
    result_hash = Hash.new { |h, k| h[k] = [] }

    countries.each do |country, _value|
      self.options.each_with_index do |_opt, index|
        result_hash[index] << User.joins('INNER JOIN answers ON users.id = answers.user_id')
                                  .where('location = ? AND answers.poll_id = ? AND answers.status = ? AND answers.answer = ?',
                                          country, self, 'active', index.to_s).count
      end
    end

    result_hash
  end

  def answers_evo
    result_hash = Hash.new(0)
    answers = Answer.where(poll: self, status: 'active').order(:created_at)

    start_date = answers.size.zero? ? Date.parse(self.created_at.to_s) : Date.parse(answers.first.created_at.to_s)
    end_date = answers.size.zero? ? Date.parse(self.deadline.to_s) : Date.parse(answers.last.created_at.to_s)
    start_date -= 1 if start_date == end_date
    date = start_date

    answer_hash = Hash.new(0)
    answer_date = answers.map { |ans| Date.parse(ans.created_at.to_s) }
    answer_input = answer_date.each { |ad| answer_hash[ad.strftime("%d.%m.%y")] += 1 }
    cumulative = 0

    until date == end_date + 1
      date_st = date.strftime("%d.%m.%y")
      cumulative += answer_hash[date_st]
      result_hash["   #{date_st}"] = cumulative
      date += 1
    end

    result_hash
  end

  def like_evo
    answers = Answer.where(poll: self, status: 'active').order(:created_at)

    start_date = answers.size.zero? ? Date.parse(self.created_at.to_s) : Date.parse(answers.first.created_at.to_s)
    end_date = answers.size.zero? ? Date.parse(self.deadline.to_s) : Date.parse(answers.last.created_at.to_s)
    start_date -= 1 if start_date == end_date
    date = start_date

    a_dates = []
    a_loved = []
    a_funny = []
    a_interest = []

    until date == end_date + 1
      a_dates << "   #{date.strftime("%d.%m.%y")}"
      a_loved << { x: " #{date.strftime('%d.%m.%y')}",
                   y: "#{ Answer.where("f_love = true AND status = 'active' AND poll_id = ? AND created_at <= ?", self.id, date + 1).count + 0.2}" }
      a_funny << { x: " #{date.strftime('%d.%m.%y')}",
                   y: "#{ Answer.where("f_funny = true AND status = 'active' AND poll_id = ? AND created_at <= ?", self.id, date + 1).count + 0.1}" }
      a_interest << { x: " #{date.strftime('%d.%m.%y')}",
                      y: "#{ Answer.where("f_interest = true AND status = 'active' AND poll_id = ? AND created_at <= ?", self.id, date + 1).count}" }

      date += 1
    end

    result_hash = {}
    result_hash[:dates] = a_dates
    result_hash[:loved] = a_loved
    result_hash[:funny] = a_funny
    result_hash[:interesting] = a_interest
    result_hash
  end

  private

  def val_options
    if options.nil? || options.class != Array
      errors.add("No answer options for the question.")
    elsif options.size < 2 || options.size > 5
      errors.add("Invalid number options for the question.")
    end
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: %i(show add_answer result report toggle destroy)
  before_action :active_categories, only: %i(index manage answered sponsored fresh loved funny interesting friend)
  before_action :quick_links, only: %i(index manage answered sponsored fresh loved funny interesting friend)

  # Listing of polls

  def index
    polls = select_polls.order('t_likes DESC, deadline ASC')
    @polls = params[:query].present? ? polls.poll_search(params[:query]) : polls
  end

  def fresh
    polls = select_polls.order('created_at DESC, deadline ASC')
    @polls = params[:query].present? ? polls.poll_search(params[:query]) : polls
  end

  def loved
    polls = select_polls.order('t_love DESC, deadline ASC')
    @polls = params[:query].present? ? polls.poll_search(params[:query]) : polls
  end

  def funny
    polls = select_polls.order('t_funny DESC, deadline ASC')
    @polls = params[:query].present? ? polls.poll_search(params[:query]) : polls
  end

  def interesting
    polls = select_polls.order('t_interest DESC, deadline ASC')
    @polls = params[:query].present? ? polls.poll_search(params[:query]) : polls
  end

  def sponsored
    polls = select_polls.where(qtype: "sponsored").order('points DESC, deadline ASC')
    @polls = params[:query].present? ? polls.poll_search(params[:query]) : polls
  end

  def manage
    polls = policy_scope(Poll).where("status != 'deleted' AND user_id = ? AND category_id IN (?)", current_user.id, @category_list).order('created_at DESC')
    @polls = params[:query].present? ? polls.poll_search(params[:query]) : polls
  end

  def answered
    # polls_answered_ids = Answer.where("status != 'deleted' AND user_id = ?", current_user.id).order('created_at DESC').pluck(:poll_id)
    # polls_answered = Poll.where('id IN (?) AND category_id IN (?)', polls_answered_ids, @category_list)

    polls_answered = Poll.joins('INNER JOIN answers ON polls.id = answers.poll_id')
                         .where('category_id IN (?) AND answers.status != ? AND answers.user_id = ?',
                          @category_list, 'deleted', current_user.id)
                         .order('answers.created_at DESC')
    @polls = params[:query].present? ? polls_answered.poll_search(params[:query]) : polls_answered
  end

  def friend
    polls = policy_scope(Poll).where("status = 'active' AND user_id = ? AND category_id IN (?)", params[:friend_id].to_i, @category_list).order('created_at DESC')
    @polls = params[:query].present? ? polls.poll_search(params[:query]) : polls
  end

  # Poll creation

  def new
    authorize Poll
    @poll = Poll.new()
  end

  def create
    authorize Poll
    question = params["np-question"].last == "?" ? params["np-question"].sub(/\S/, &:upcase) : params["np-question"].sub(/\S/, &:upcase) + "?"
    @poll = Poll.new(user: current_user,
                    category_id: params["np-category"].to_i,
                    points: params["np-tickets"].to_i,
                    qtype: params["np-qtype"],
                    question: question,
                    optype: "SCP",
                    options: [params["np-opt-1"].sub(/\S/, &:upcase),
                              params["np-opt-2"].sub(/\S/, &:upcase),
                              params["np-opt-3"].sub(/\S/, &:upcase),
                              params["np-opt-4"].sub(/\S/, &:upcase),
                              params["np-opt-5"].sub(/\S/, &:upcase)]
                              .reject! { |s| s.nil? || s.strip.empty? },
                    tags: params["np-tags"].gsub(/, /, ",").split(",").each { |t| t.sub(/\S/, &:upcase) },
                    deadline: Time.parse(params["np-deadline"]))
    if @poll.save
      redirect_to manage_polls_path
    else
      render :new
    end
  end

  # Poll detail

  def show
    authorize Poll
  end

  # Poll answer workflow

  def add_answer
    if params["poll-id-#{@poll.id}"].present?
      new_answer = Answer.new(user: current_user,
                              poll: @poll,
                              points: @poll.points,
                              answer: params["poll-id-#{@poll.id}"],
                              f_love: params["icon-love-#{@poll.id}"] == "on",
                              f_funny: params["icon-funny-#{@poll.id}"] == "on",
                              f_interest: params["icon-interesting-#{@poll.id}"] == "on")
      new_answer.save!
      @poll.refresh_likes
    else
      flash[:alert] = "No valid answer selected for the poll."
    end
  end

  def result
    @results = @poll.results
    @answer = @poll.answer(current_user)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def report
    new_report = Report.new(user: current_user, poll: @poll)
    new_report.save!
    redirect_to(controller: 'polls', action: params[:origin_action])
  end

  # Poll inactivation

  def toggle
    if @poll.status == 'active'
      @poll.status = 'inactive'
    elsif @poll.status == 'inactive'
      @poll.status = 'active'
    end
    @poll.save!
    redirect_to(controller: 'polls', action: params[:origin_action])
  end

  def destroy
    @poll.answers.destroy_all
    @poll.destroy
    redirect_to(controller: 'polls', action: params[:origin_action])
  end

  private

  def select_polls
    polls_answered = Answer.where("status != 'deleted' AND user_id = ?", current_user.id).pluck(:poll_id)
    polls_reported = Report.where("status != 'deleted' AND user_id = ?", current_user.id).pluck(:poll_id)
    polls_fetch = policy_scope(Poll).where("status = 'active' AND user_id != ? AND deadline > ? AND category_id IN (?)", current_user.id, Time.now, @category_list)
    polls_selection = polls_answered.size.zero? ? polls_fetch : polls_fetch.where("id NOT IN (?)", polls_answered)
    polls = polls_reported.size.zero? ? polls_selection : polls_selection.where("id NOT IN (?)", polls_reported)
  end

  def active_categories
    @category_list = []
    Category.all.each do |cat|
      filter = Filter.find_by(category: cat, user: current_user)
      @category_list << cat.id if filter.nil? || filter.active
    end
  end

  def quick_links
    return if current_user.nil?

    @quick_links = current_user.hobbies.empty? ? [] : current_user.hobbies.split(", ").map { |hob| hob.downcase.capitalize }
    all_tags = Poll.where('status = ? AND deadline > ?', 'active', Time.now).pluck(:tags).flatten
    hot_tags = Hash.new(0)
    all_tags.each { |tag| hot_tags[tag.downcase.capitalize] += 1 }
    hot_tags.sort_by { |_tag, value| value }.each { |tag, _value| @quick_links << tag }
    @quick_links
  end

  def set_poll
    @poll = Poll.find(params[:id])
  end

  def poll_params
    params.require(:poll).permit(:id)
  end
end

app/views/polls/answered.html.erb
<%= render 'shared/index-page', polls: @polls %>

app/views/polls/fresh.html.erb
<%= render 'shared/index-page', polls: @polls %>

app/views/polls/friend.html.erb
<%= render 'shared/index-page', polls: @polls %>

app/views/polls/funny.html.erb
<%= render 'shared/index-page', polls: @polls %>

app/views/polls/index.html.erb
<div class="container list-page">

    <div class="column left-column">
      <%= render 'shared/sidebar' %>
    </div>

    <div class="column center-column">
      <%= render 'shared/pollist', locals: {polls: @polls}  %>
    </div>

    <div class="column right-column">
      <%= render 'shared/filters' %>
    </div>

</div>

app/views/polls/interesting.html.erb
<%= render 'shared/index-page', polls: @polls %>

app/views/polls/loved.html.erb
<%= render 'shared/index-page', polls: @polls %>

app/views/polls/manage.html.erb
<%= render 'shared/index-page', polls: @polls %>

app/views/polls/new.html.erb
<div class="form-main with-nav new-poll">

  <div class="page-header">
    <h2><i class="fas fa-plus-square"></i> New Poll</h2>
  </div>

  <form action="/polls" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

    <div class="form-inputs">

      <div class="form-group row">
        <label for="np-question" class="col-xs-12 col-md-2 col-form-label">Question</label>
        <div class="col-xs-12 col-md-10">
          <textarea id="np-question" name="np-question" placeholder="What is your question?" minlength="10" maxlength="60" required></textarea>
        </div>
      </div>

      <div class="form-group row">
        <label for="np-tags" class="col-xs-12 col-md-2 col-form-label col-form-label">Tags</label>
        <div class="col-xs-12 col-md-10">
          <input type="text" id="np-tags" name="np-tags" placeholder="Series, GoT, GoT Season 8" maxlength="45">
        </div>
      </div>

      <div class="form-group row">
        <label for="np-category" class="col-xs-12 col-md-2 col-form-label col-form-label">Category</label>
        <div class="col-xs-12 col-md-6">
          <select id="np-category" name="np-category" placeholder="Main category" required>
            <option value="" class="placeholder-fm" disabled selected>Select from list...</option>
            <% Category.all.each do |cat| %>
              <option value="<%= cat.id %>">
                <%= cat.name %><%= image_tag("category_white/#{cat.icon}") %>
              </option>
            <% end %>
          </select>
        </div>
      </div>

      <div class="form-group row">
        <label for="np-answers" class="col-xs-6 col-md-2 col-form-label col-form-label">Options</label>
        <div class="col-xs-6 col-md-2">
          <input type="number" value="2" min="2" max="5" id="np-answers" name="np-answers" class="text-center" required>
        </div>

        <div class="col-xs-12 col-md-4 hidden">
          <select id="np-option-type" name="np-option-type" placeholder="option type" required value="SCP" disabled>
            <option value="SCP">Single Choice</option>
            <option value="MCP">Multiple Choice</option>
          </select>
        </div>
      </div>

      <div class="np-options">

        <div class="form-group row np-opt-group">
          <label for="np-opt-1" class="col-xs-12 col-md-2 col-form-label col-form-label"></label>
          <div class="col-xs-12 col-md-10">
            <input type="text" class="np-opt" id="np-opt-1" name="np-opt-1" data-op="1" placeholder="Option 1" minlength="1" maxlength="30" required>
          </div>
        </div>

        <div class="form-group row np-opt-group">
          <label for="np-opt-2" class="col-xs-12 col-md-2 col-form-label col-form-label"></label>
          <div class="col-xs-12 col-md-10">
            <input type="text" class="np-opt" id="np-opt-2" name="np-opt-2" data-op="2" placeholder="Option 2" minlength="1" maxlength="30" required>
          </div>
        </div>

        <div class="form-group row np-opt-group hidden">
          <label for="np-opt-3" class="col-xs-12 col-md-2 col-form-label col-form-label"></label>
          <div class="col-xs-12 col-md-10">
            <input type="text" class="np-opt hidden" id="np-opt-3" name="np-opt-3" data-op="3" placeholder="Option 3" minlength="1" maxlength="30">
          </div>
        </div>

        <div class="form-group row np-opt-group hidden">
          <label for="np-opt-4" class="col-xs-12 col-md-2 col-form-label col-form-label"></label>
          <div class="col-xs-12 col-md-10">
            <input type="text" class="np-opt hidden" id="np-opt-4" name="np-opt-4" data-op="4" placeholder="Option 4" minlength="1" maxlength="30">
          </div>
        </div>

        <div class="form-group row np-opt-group hidden">
          <label for="np-opt-5" class="col-xs-12 col-md-2 col-form-label col-form-label"></label>
          <div class="col-xs-12 col-md-10">
            <input type="text" class="np-opt hidden" id="np-opt-5" name="np-opt-5" data-op="5" placeholder="Option 5" minlength="1" maxlength="30">
          </div>
        </div>

      </div>

      <div class="form-group row">
        <label for="np-qtype" class="col-xs-hidden col-md-2 col-form-label col-form-label">Type</label>
        <div class="col-xs-12 col-md-4">
          <select id="np-qtype" name="np-qtype" required <%= 'disabled' if current_user.subscription == 'free' %>>
            <option value="open">Open</option>
            <option value="closed" <%= 'disabled' if current_user.subscription == 'free' %>>Closed</option>
            <option value="pro" <%= 'disabled' if current_user.subscription != 'pro' %>>Sponsored</option>
          </select>
        </div>
      </div>

      <div class="form-group row">
        <label for="np-deadline" class="col-xs-12 col-md-2 col-form-label col-form-label">Deadline</label>
        <div class="col-xs-12 col-md-4">
          <input class="text-center form-picker" type="text" id="np-deadline" name="np-deadline" value="<%= Date.today + 8 %>" required <%= 'disabled' if current_user.subscription == 'free' %>>
        </div>
      </div>

      <div class="form-group row">
        <label for="np-tickets" class="col-xs-12 col-md-2 col-form-label col-form-label">Tickets</label>
        <div class="col-xs-12 col-md-2 text-center">
          <input class="text-center" type="number" id="np-tickets" name="np-tickets" value="1" min="1" max="99" required <%= 'disabled' if current_user.subscription != 'pro' %>>
        </div>
        <p id="poll-price"></p>
      </div>
    </div>

    <div class="form-actions">
      <% if current_user.subscription == 'free' %>
        <%= link_to go_premium_path, class:"btn btn-clear" do %>
          Upgrade to Premium
        <% end %>
      <% elsif current_user.subscription == 'premium' %>
        <%= link_to go_pro_path, class:"btn btn-clear" do %>
          Upgrade to Pro
        <% end %>
      <% end %>
      <button type="submit" class="btn">Create</button>
    </div>

  </form>

</div>

app/views/polls/polls.html.erb
<%= render 'shared/index-page', polls: @polls %>

app/views/polls/result.html.erb
<%= render 'shared/poll_components/chart', object: {poll_id: @poll.id} %>

app/views/polls/result.js.erb
const cardFront = document.querySelector(`#poll-card-front-${id}`);
const cardBack = document.querySelector(`#poll-card-back-${id}`);
const cardStats = document.querySelector(`#poll-card-stats-${id}`);
setTimeout(function() {
  cardFront.classList.add("unflipped");
  if (cardFront.dataset.answered === 'false') {
    cardBack.classList.remove("unflipped");
  } else {
    const partialRenderHtml = `<%= j render('shared/poll_components/chart', object: {poll_id: ${id}}) %>`;
    const chartArea = document.querySelector(`#chart-area-${id}`);
    chartArea.html(partialRenderHtml);
    cardStats.classList.remove("unflipped");
  }
}, (400));

app/views/polls/show.html.erb
<% @poll.refresh_likes %>

<div class="container list-page dash-page show-page">
  <div class="column center-column">

    <div class="page-header">
      <h2><i class="fas fa-chart-area"></i> Poll Stats</h2>
      <div class="dash-btn" style="display:flex; max-width: 400px; margin: 1rem auto;">
        <%= link_to ' Back '.html_safe, :back, class: "btn btn-back" %>
      </div>
    </div>

    <div class="show-container container-fluid">

      <h3 class="title"><%= @poll.question %></h3>

      <nav>
        <div class="nav nav-pills" id="nav-tab" role="tablist">
          <a class="nav-link active" id="nav-bi-tab" data-toggle="tab" href="#nav-bi" role="tab" aria-controls="nav-bi" aria-selected="true">Basic Info</a>
          <a class="nav-link <%= 'disabled' if (current_user.subscription == 'free') %>" id="nav-as-tab" data-toggle="tab" href="#nav-as" role="tab" aria-controls="nav-as" aria-selected="false">Analytics</a>
          <a class="nav-link <%= 'disabled' unless (current_user.subscription == 'pro' && current_user == @poll.user ) %>" id="nav-ad-tab" data-toggle="tab" href="#nav-ad" role="tab" aria-controls="nav-ad" aria-selected="true">Answers</a>
        </div>
      </nav>

      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-bi" role="tabpanel" aria-labelledby="nav-bi-tab">
          <%= render 'shared/show_components/basic-info' %>
        </div>

        <div class="tab-pane fade" id="nav-as" role="tabpanel" aria-labelledby="nav-as-tab">
          <%= render 'shared/show_components/analytics' %>
        </div>

        <div class="tab-pane fade" id="nav-ad" role="tabpanel" aria-labelledby="nav-ad-tab">
          <div class="show-row row">
            <div class="show-comp show-comp-large col-12">
              <!-- <h3>User Info</h3> -->

              <ul class="show-users">
                <li style="height:0"></li>
                <% Answer.where(poll: @poll, status: 'active').order('created_at DESC').each do |ans| %>
                  <% user = ans.user %>
                  <% goto = user == current_user ? dash_path : friend_fdash_path(friend_id: user.id) %>
                  <%= link_to goto do %>
                    <li style="display: flex; align-items: center" class="desktop">
                      <div style="width:10%;max-width:10%;min-width:10%">

                        <% if user.photo.file.nil? %>
                          <%= image_tag "avatar/#{user.birthdate.day}.svg", size: "40x40" %>
                        <% else %>
                          <%= cl_image_tag("#{user.photo}", size: "40x40", crop: :thumb, gravity: :face, class: "svg-icon") %>
                        <% end %>

                      </div>
                      <div style="width:20%;max-width:20%;min-width:20%"><strong><%= user.first_name %> <%= user.last_name %></strong></div>
                      <div style="flex-grow: 1"><em><%= @poll.options[ans.answer.to_i].sub(/\S/, &:upcase) %></em></div>
                      <div style="width:20%;max-width:20%;min-width:20%;text-align:center"><%= ans.created_at.strftime('%d.%m.%y %H:%M') %></div>
                      <div style="width:5%;max-width:5%;min-width:5%;text-align:center">
                        <span title="Loved" data-toggle="tooltip-all">
                          <i class="fas fa-heart fa-xl" style="color: <%= ans.f_love == true ? 'rgb(140,140,140)' : 'rgb(230,230,230)' %>"></i>
                        </span>
                      </div>
                      <div style="width:5%;max-width:5%;min-width:5%;text-align:center">
                        <span title="Funny" data-toggle="tooltip-all">
                          <i class="fas fa-grin-squint fa-xl" style="color: <%= ans.f_funny == true ? 'rgb(140,140,140)' : 'rgb(230,230,230)' %>"></i>
                        </span>
                      </div>
                      <div style="width:5%;max-width:5%;min-width:5%;text-align:center;margin-right:1rem">
                        <span title="Interesting" data-toggle="tooltip-all">
                          <i class="fas fa-graduation-cap fa-xl" style="color: <%= ans.f_interest == true ? 'rgb(140,140,140)' : 'rgb(230,230,230)' %>"></i>
                        </span>
                      </div>
                    </li>

                    <li style="text-align: center" class="mobile">
                      <div><strong><%= user.first_name %> <%= user.last_name %></strong></div>
                      <div><em><%= @poll.options[ans.answer.to_i].sub(/\S/, &:upcase) %></em></div>
                      <div><%= ans.created_at.strftime('%d.%m.%y %H:%M') %></div>
                      <div>
                        <span title="Loved" data-toggle="tooltip-all" style="margin-right: 0.5rem">
                          <i class="fas fa-heart" style="color: <%= ans.f_love == true ? 'rgb(140,140,140)' : 'rgb(230,230,230)' %>"></i>
                        </span>
                        <span title="Funny" data-toggle="tooltip-all" style="margin-right: 0.5rem">
                          <i class="fas fa-grin-squint" style="color: <%= ans.f_funny == true ? 'rgb(140,140,140)' : 'rgb(230,230,230)' %>"></i>
                        </span>
                        <span title="Interesting" data-toggle="tooltip-all">
                          <i class="fas fa-graduation-cap" style="color: <%= ans.f_interest == true ? 'rgb(140,140,140)' : 'rgb(230,230,230)' %>"></i>
                        </span>
                      </div>

                    </li>
                  <% end %>
                <% end %>
              </ul>

            </div>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/polls/sponsored.html.erb
<%= render 'shared/index-page', polls: @polls %>