config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  as :user do
    get 'users', to: "profiles#dash", as: :user_root
  end

  get :dash, to: "profiles#dash"
  get :go_premium, to: "profiles#go_premium", as: :go_premium
  get :go_pro, to: "profiles#go_pro", as: :go_pro
  get :ftoggle, to: "profiles#filter_toggle", as: :ftoggle
  get :filters, to: "profiles#filters", as: :filters
  get :filterall, to: "profiles#filter_all", as: :filterall

  resources :polls, except: [:edit, :update] do
    member do
      post :answer, to: "polls#add_answer"
      get :toggle, to: "polls#toggle"
      post :result, to: "polls#result"
      get :share, to: "polls#share"
      get :report, to: "polls#report"
    end

    collection do
      get :manage, to: "polls#manage", as: :manage
      get :answered, to: "polls#answered", as: :answered
      get :sponsored, to: "polls#sponsored", as: :sponsored
      get :fresh, to: "polls#fresh", as: :fresh
      get :loved, to: "polls#loved", as: :loved
      get :funny, to: "polls#funny", as: :funny
      get :interesting, to: "polls#interesting", as: :interesting
      get :friend, to: "polls#friend", as: :friend
    end
  end

  resources :friends, only: :index do
    get :add, to: "friends#add", as: :add
    get :remove, to: "friends#remove", as: :remove
    get :block, to: "friends#block", as: :block
    get :dash, to: "friends#dash", as: :fdash
  end
end

app/views/shared/poll_components/_avatar.html.erb
<% poll = object[:poll] %>

<div class="avatar-drop dropleft">

  <% if poll.user.photo.file.nil? %>
    <%= image_tag "avatar/#{poll.user.birthdate.day}.svg", size: "36x36", class: "dropdown-toggle", alt: "#{poll.user.first_name} #{poll.user.last_name}", role: "button", id: "dropdownMenuUser", data: {toggle: "dropdown"}, 'aria-haspopup': true, 'aria-expanded': false %>
  <% else %>
    <%= cl_image_tag("#{poll.user.photo}", size: "36x36", crop: :thumb, gravity: :face, class: "svg-icon dropdown-toggle", alt: "#{poll.user.first_name} #{poll.user.last_name}", role: "button", id: "dropdownMenuUser", data: {toggle: "dropdown"}, 'aria-haspopup': true, 'aria-expanded': false) %>
  <% end %>

  <% unless action_name == "friend" || action_name == "manage" %>

    <div class="dropdown-menu dropdown-avatar" aria-labelledby="dropdownMenuUser">
      <%= poll.user.first_name %> <%= poll.user.last_name %>
      <div class="options">

        <% rs = Friend.where(active_user_id: current_user.id, follow_user_id: poll.user.id).last %>

        <% if poll.user == current_user %>
        <% elsif rs.nil? || rs.status == 'inactive' %>
          <%= link_to '<i class="fas fa-user-plus"></i>'.html_safe, friend_add_path(poll.user.id), class: "drop-option", title: "Follow", data: { toggle: "tooltip-bottom", placement: "bottom" } %>
        <% elsif controller_name != 'friends' && rs.status != 'blocked' %>
          <%= link_to '<i class="fas fa-tachometer-alt"></i>'.html_safe, friend_fdash_path(friend_id: poll.user.id), class: "drop-option", title: "Dashboard", data: { toggle: "tooltip-bottom", placement: "bottom" } %>
          <%= link_to '<i class="fas fa-poll-h"></i>'.html_safe, friend_polls_path(friend_id: poll.user.id), class: "drop-option", title: "Polls", data: { toggle: "tooltip-bottom", placement: "bottom" } %>
          <%#= link_to '<i class="fas fa-user-minus"></i>'.html_safe, friend_remove_path(poll.user.id), class: "drop-option", title: "Remove", data: { toggle: "tooltip-bottom", placement: "bottom" } %>
        <% end %>

        <%= link_to '<i class="fas fa-search"></i>'.html_safe, ({controller: controller_name, action: action_name, query: "#{poll.user.first_name} #{poll.user.last_name}"}), class: "drop-option", title: "Filter", data: { toggle: "tooltip-bottom", placement: "bottom" } %>
      </div>
    </div>

  <% end %>

</div>

app/views/shared/poll_components/_backarrow.html.erb
<% poll = object[:poll] %>

<i class="fas fa-arrow-left go-back" data-poll="<%= poll.id %>" style="color: #C5C5C5"></i>

app/views/shared/poll_components/_chart.html.erb
<% poll = Poll.find(object[:poll_id]) %>
<% cat_color = poll.category.color %>

<div class="poll-frame poll-frame-stats" style="<%= "border-color: #{cat_color}; background-color: #{cat_color}; color: white;" %>" id="myChart-area-<%= poll.id %>">

  <canvas id="myChart-<%= poll.id %>" ></canvas>

  <% poll_options = poll.options.map { |option| option.length > 12 ? "  #{option[0,12].sub(/\S/, &:upcase)}.." : "  #{option.sub(/\S/, &:upcase)}" } %>
  <% poll_options.each { |po| po.strip if poll.options.count > 3 } %>

  <% unless poll.answers.count.zero? %>

    <% my_answer = poll.answers.last %> <!-- poll.answer(current_user).last -->
    <% answer_index = my_answer.answer.to_i %>
    <% bar_colors = Array.new(poll.options.length, 'rgba(240, 240, 240, 0.2)') %>
    <% bar_colors[answer_index] = 'rgba(240, 240, 240, 1)' %>
    <% bar_line_colors = Array.new(poll.options.length, 'rgba(240, 240, 240, 0.6)') %>

    <% if poll.options.count > 3 %>

    <!-- Bar Chart -->
      <script>
        Chart.defaults.global.defaultFontColor = 'rgba(240, 240, 240, 1)';
        Chart.defaults.global.defaultFontFamily = 'Quicksand', "Helvetica", "sans-serif";
        Chart.defaults.global.defaultFontSize = 12;

        var ctx = document.getElementById(`myChart-<%= poll.id %>`).getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'horizontalBar',
            data: {
                labels: <%= poll_options.to_json.html_safe %>,
                fillOpacity: .8,
                datasets: [{
                    label: '',
                    data: <%= poll.results.values.to_json.html_safe %>,
                    backgroundColor: <%= bar_colors.to_json.html_safe %>,
                    borderColor: <%= bar_line_colors.to_json.html_safe %>,
                    borderWidth: 1
                }]
            },
            animation:{
              duration: 1
            },
            options: {
              legend: {
                display: false
              },
              responsive: true,
              maintainAspectRatio: false,
              scales: {
                  xAxes: [{
                      ticks: {
                          beginAtZero: true,
                          display: false
                      },
                      gridLines: {
                          drawBorder: false,
                          display:false
                      }
                  }],
                  yAxes: [{
                      ticks: {
                          maxRotation: 0,
                          minRotation: 0
                      },
                      gridLines: {
                          display:false,
                          color: 'rgba(240, 240, 240, 1)'
                      },
                  }]
              }
            }
        });
      </script>
    <!--  -->

    <% else %>

    <!-- Pie Chart -->
      <script>
        Chart.defaults.global.defaultFontColor = 'rgba(240, 240, 240, 1)';
        Chart.defaults.global.defaultFontFamily = 'Quicksand', "Helvetica", "sans-serif";
        Chart.defaults.global.defaultFontSize = 12;

        var ctx = document.getElementById(`myChart-<%= poll.id %>`).getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'doughnut',
            data: {
                labels: <%= poll_options.to_json.html_safe %>,
                datasets: [{
                    label: '',
                    data: <%= poll.results.values.to_json.html_safe %>,
                    backgroundColor: <%= [
                        "#{answer_index == 0 ? 'rgba(240, 240, 240, 1)' : 'rgba(210, 210, 210, 0.5)'}",
                        "#{answer_index == 1 ? 'rgba(240, 240, 240, 1)' : 'rgba(160, 160, 160, 0.5)'}",
                        "#{answer_index == 2 ? 'rgba(240, 240, 240, 1)' : 'rgba(110, 110, 110, 0.5)'}"
                    ].take(poll.options.length).to_json.html_safe %> ,
                    borderColor: <%= Array.new(poll.options.length, 'rgba(240, 240, 240, 1)').to_json.html_safe %>,
                    borderWidth: 1
                }]
            },
            animation:{
              duration: 1
            },
            options: {
              legend: {
                position: 'bottom',
              },
              responsive: true,
              maintainAspectRatio: false
            }
        });
      </script>
    <!--  -->

    <% end %>

  </div>

  <div class="poll-bottom">
    <div class="poll-bottom-left">
      <p title="Answered On" data-toggle="tooltip-all">
        <i class="far fa-calendar-check"></i>
        <%= my_answer.created_at.strftime("%d.%m.%y %H:%M") %>
      </p>
    </div>

    <div class="poll-bottom-right">
      <span title="Loved" data-toggle="tooltip-all">
        <i class="fas fa-heart fa-sm" style="color: <%= my_answer.f_love == true ? 'rgb(140,140,140)' : 'rgb(230,230,230)' %>"></i>
      </span>

      <span title="Funny" data-toggle="tooltip-all">
        <i class="fas fa-grin-squint fa-sm" style="color: <%= my_answer.f_funny == true ? 'rgb(140,140,140)' : 'rgb(230,230,230)' %>"></i>
      </span>

      <span title="Interesting" data-toggle="tooltip-all">
        <i class="fas fa-graduation-cap fa-sm" style="color: <%= my_answer.f_interest == true ? 'rgb(140,140,140)' : 'rgb(230,230,230)' %>"></i>
      </span>
    </div>

  <% end %>

</div>

app/views/shared/poll_components/_dropleft.html.erb
<% poll = object[:poll] %>

<div class="dropleft dropleft-options">

  <%= link_to '<i class="fas fa-ellipsis-h more-info"></i>'.html_safe, "#", class: "dropdown-toggle", role: "button", id: "dropdownMenuLink", data: {toggle: "dropdown"}, 'aria-haspopup': true, 'aria-expanded': false %>

  <div class="dropdown-menu pull-left dropdown-card" aria-labelledby="dropdownMenuLink">

    <% if poll.user == current_user || (poll.qtype == 'open' && poll.answered?(current_user)) %>
      <%= link_to '<i class="fas fa-chart-area"></i>'.html_safe, poll_path(poll, origin_action: action_name), class: "drop-option", title: "Stats", data: { toggle: "tooltip" } %>
    <% end %>

    <% if poll.user == current_user && poll.status == 'active' %>
      <%= link_to '<i class="fas fa-eye-slash"></i>'.html_safe, toggle_poll_path(poll, origin_action: action_name), class: "drop-option", title: "Hide", data: { toggle: "tooltip" } %>
    <% end %>

    <% if poll.user == current_user && poll.status == 'inactive' %>
      <%= link_to '<i class="fas fa-eye"></i>'.html_safe, toggle_poll_path(poll, origin_action: action_name), class: "drop-option", title: "Show", data: { toggle: "tooltip" } %>
    <% end %>

    <% if poll.user == current_user %>
      <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, poll_path(poll, origin_action: action_name), method: :delete, class: "drop-option", title: "Delete", data: { toggle: "tooltip", confirm: "Are you sure you want to permanently delete this poll and all its messages?" } %>
    <% end %>

    <% unless poll.user == current_user %>
      <%= link_to '<i class="fas fa-exclamation-circle"></i>'.html_safe, report_poll_path(poll, origin_action: action_name), class: "drop-option", title: "Report Abuse", data: { toggle: "tooltip", confirm: "Are you sure you want to report this poll and its user?" } %>
    <% end %>

  </div>

</div>